# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import qdina_pb2 as protos_dot_qdina__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/qdina_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QDinaServiceStub:
    """Service definition for network coordination
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/qdina.QDinaService/RegisterWorker',
                request_serializer=protos_dot_qdina__pb2.WorkerRegistration.SerializeToString,
                response_deserializer=protos_dot_qdina__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.SubmitMetricsAndGetWorkload = channel.unary_unary(
                '/qdina.QDinaService/SubmitMetricsAndGetWorkload',
                request_serializer=protos_dot_qdina__pb2.LocalMetrics.SerializeToString,
                response_deserializer=protos_dot_qdina__pb2.WorkloadSlice.FromString,
                _registered_method=True)


class QDinaServiceServicer:
    """Service definition for network coordination
    """

    def RegisterWorker(self, request, context):
        """Worker node registers with the master router at startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitMetricsAndGetWorkload(self, request, context):
        """Worker sends its local metrics and awaits the next workload slice
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QDinaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=protos_dot_qdina__pb2.WorkerRegistration.FromString,
                    response_serializer=protos_dot_qdina__pb2.RegistrationResponse.SerializeToString,
            ),
            'SubmitMetricsAndGetWorkload': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMetricsAndGetWorkload,
                    request_deserializer=protos_dot_qdina__pb2.LocalMetrics.FromString,
                    response_serializer=protos_dot_qdina__pb2.WorkloadSlice.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qdina.QDinaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qdina.QDinaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QDinaService:
    """Service definition for network coordination
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qdina.QDinaService/RegisterWorker',
            protos_dot_qdina__pb2.WorkerRegistration.SerializeToString,
            protos_dot_qdina__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitMetricsAndGetWorkload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qdina.QDinaService/SubmitMetricsAndGetWorkload',
            protos_dot_qdina__pb2.LocalMetrics.SerializeToString,
            protos_dot_qdina__pb2.WorkloadSlice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
