# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/qdina.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protos/qdina.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/qdina.proto\x12\x05qdina\"H\n\x12WorkerRegistration\x12\x12\n\nreplica_id\x18\x01 \x01(\x05\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"7\n\x14RegistrationResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"s\n\x0cLocalMetrics\x12\x12\n\nreplica_id\x18\x01 \x01(\x05\x12\x12\n\ntotal_cost\x18\x02 \x01(\x01\x12\r\n\x05\x63osts\x18\x03 \x03(\x01\x12\x14\n\x0cstorage_used\x18\x04 \x01(\x01\x12\x16\n\x0e\x61\x63tive_indexes\x18\x05 \x03(\t\"7\n\rWorkloadSlice\x12\x15\n\rstop_training\x18\x01 \x01(\x08\x12\x0f\n\x07queries\x18\x02 \x03(\t2\xa2\x01\n\x0cQDinaService\x12H\n\x0eRegisterWorker\x12\x19.qdina.WorkerRegistration\x1a\x1b.qdina.RegistrationResponse\x12H\n\x1bSubmitMetricsAndGetWorkload\x12\x13.qdina.LocalMetrics\x1a\x14.qdina.WorkloadSliceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.qdina_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERREGISTRATION']._serialized_start=29
  _globals['_WORKERREGISTRATION']._serialized_end=101
  _globals['_REGISTRATIONRESPONSE']._serialized_start=103
  _globals['_REGISTRATIONRESPONSE']._serialized_end=158
  _globals['_LOCALMETRICS']._serialized_start=160
  _globals['_LOCALMETRICS']._serialized_end=275
  _globals['_WORKLOADSLICE']._serialized_start=277
  _globals['_WORKLOADSLICE']._serialized_end=332
  _globals['_QDINASERVICE']._serialized_start=335
  _globals['_QDINASERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
